language: node_js
sudo: required
node_js:
  - 8.11.1
cache:
  directories:
    - node_modules
script:
    - npm run docs:build
after_script:
    - cd docs/.vuepress/dist
    - git init
    - git add -A
    - git commit -m 'deploy'
    - git push -f https://${access_token}@github.com/BaoTao1997/BaoTao1997.github.io.git master
